### ISSUE TITLE
What the shape of the test data?

### ISSUE THREAD

**Issue by cellimnet** [YingChen7/SELMA3D_challenge-submission-example#3]
Hi Ying,
Thank you for sharing the submission example. In the inference.py, the shape of input image provided for test_run is (1, 1) and the output is (4,2), so what is the real shape of the input and output? Can i use "brain_microscopy_image = numpy.ones((8, 300, 300, 300), dtype=numpy.uint8)" to test my script?
Thanks!

**Comment by YingChen7** [comment]
Hi cellimnet,

The input image provided, with a shape of (1, 1), does not reflect the actual input shape. In the preliminary test phase, the patch size is set to 100x100x100, while in the final test phase, it is 200x200x200. You can adjust the "brain_microscopy_image" accordingly to test your script.

As for the output, the line "# For now, let us set make bogus predictions biological_brain_structure = numpy.eye(4, 2)" is just a placeholder for where your solution should be implemented. The output shape should match the size of the input.

**Comment by cellimnet** [comment]
Hi Ying,
Thank you for your answering! Now, i suppose the shape of brain_microscopy_image  after " brain_microscopy_image = load_image_file_as_array(location=INPUT_PATH / "images/3d-brain-microscopy") is (N, 100, 100, 100), N means the number of images, but I received a failure message indicating during my Docker submission, "The algorithm failed on one or more cases." Could you give me more information about the shape of the brain_microscopy_image? Does it read in one by one or as a whole?

**Comment by YingChen7** [comment]
Hi celliment,

Grand Challenge will run tests on each image individually. Therefore, the shape should represent that of a single image or patch, without the number of patches.

**Comment by cellimnet** [comment]
Hi Ying,
Thanks for your answering!
